server:
  port: 8081

spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/commercex_auth
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    health:
      show-details: always