server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/commercex_inventory
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

  endpoint:
    health:
      show-details: always