spring:

  application:
    name: order-service

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888


commercex:
  services:
    inventory:
      url: http://${INVENTORY_HOST:localhost}:8083

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss.SSS}
      [%thread]
      %-5level
      [%X{X-Correlation-ID}]
      %logger{36}
      -
      %msg%n


order-service:
  build:
    context: .
    dockerfile: services/order-service/Dockerfile