server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  cloud:
    gateway:
      server:
        webflux:

          routes:

            # ==============================
            # AUTH SERVICE
            # ==============================

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**


            # ==============================
            # PRODUCT SERVICE
            # ==============================

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**


            # ==============================
            # INVENTORY SERVICE
            # ==============================

            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**


            # ==============================
            # ORDER SERVICE
            # ==============================

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**


            # ==============================
            # PAYMENT SERVICE - FUTURE
            # ==============================

            # - id: payment-service
            #   uri: lb://PAYMENT-SERVICE
            #   predicates:
            #     - Path=/api/v1/payments/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
          - prometheus

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.server: DEBUG

api-gateway:
  build:
    context: .
    dockerfile: infrastructure/api-gateway/Dockerfile